name: "Build"
description: "Executes a compilation."

runs:
  using: "composite"
  steps:
    - name: Install libcjson-dev
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y libcjson-dev

    - name: Install Prometheus C Client
      shell: bash
      run: |
        # Usar el script de instalación del lab1
        chmod +x ./lab1/install.sh
        cd lab1 && ./install.sh

    - name: Compile
      shell: bash
      run: |
        SRC_FOLDER=$(pwd)/src
        echo "Running command: cmake -DRUN_COVERAGE=1 .. && make -j2"
        mkdir -p build && cd build
        cmake -DRUN_COVERAGE=1 -DENABLE_CJSON_TEST=OFF .. && make -j2
