name: "Test and coverage check"
description: "Test and coverage check with gcovr, pass if coverage is greater than 20%"

runs:
  using: "composite"
  steps:
    - name: "Run coverage"
      shell: bash
      run: |
        PROJECT_PATH=$(pwd)
        ERROR_FILE_FLAG=$PROJECT_PATH/tests_errors.txt
        CTEST_ERROR_FILE_FLAG=$PROJECT_PATH/ctest_errors.txt

        echo "Contenido de build:"
        ls -l build

        echo "Contenido de build/tests:"
        ls -l build/tests

        CTEST_COMMAND=$(ctest --test-dir build --output-on-failure -VV 2> $CTEST_ERROR_FILE_FLAG 1>$ERROR_FILE_FLAG)

        if [ -s $CTEST_ERROR_FILE_FLAG ]; then
          echo "Error: Unit Tests Failed"
          exit 1
        else
          echo "All tests were passed!"
        fi

        gcovr -r $PROJECT_PATH . >> $ERROR_FILE_FLAG

        echo "Running: gcovr -r $PROJECT_PATH ."
        cat $ERROR_FILE_FLAG

        COVERAGE_RESULT=$(grep "TOTAL" $ERROR_FILE_FLAG | awk '{print $NF}' | cut -d '%' -f 1)

        if [ "$(echo "$COVERAGE_RESULT > 5" | bc)" -eq 1 ]; then
          echo "Coverage is greater than 5%. Nice!"
          exit 0
        else
          echo "Error: Coverage is less than or equal to 5%"
          exit 1
        fi

    # Upload errors as an artifact, when failed
    - uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: Tests or coverage errors!!!
        path: ./tests_errors.txt
        retention-days: 1
